INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: ITIL Runbooks
repo_url: https://gitlab.com/nofusscomputing/infrastructure/configuration-management/itil_runbooks
edit_uri: '/-/ide/project/nofusscomputing/infrastructure/configuration-management/itil_runbooks/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - ITIL:

    - Runbooks: 

      - projects/itil/runbooks/index.md

      - AWX:

        - projects/itil/runbooks/awx/add_execution_hop_node.md

        - projects/itil/runbooks/awx/install_remote_execution_node.md

      - GIT:

        - projects/itil/runbooks/git/project_config.md

      - GLPI:

        - projects/itil/runbooks/glpi/appliance_add.md

        - projects/itil/runbooks/glpi/computer_add.md

        - projects/itil/runbooks/glpi/software_add.md

        - Plugins:

          - Form Creator:

            - projects/itil/runbooks/glpi/plugins/form_creator_new_form.md

        - projects/itil/runbooks/glpi/ticket_triage.md

      - Kubernetes:

          - projects/itil/runbooks/kubernetes/failed_to_connect_to_api.md

      - Linux:

          - projects/itil/runbooks/linux/custom_ca.md

      - PHPIPAM:

          - projects/itil/runbooks/phpipam/device_add.md

          - projects/itil/runbooks/phpipam/scanagent_add.md

      - Service Catalog:

          - projects/itil/runbooks/service_catalog/new_user.md

- Operations: 

  - operations/index.md

- Contact Us: contact.md
