INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: ITIL Runbooks
repo_url: https://gitlab.com/nofusscomputing/infrastructure/configuration-management/itil_runbooks
edit_uri: '/-/ide/project/nofusscomputing/infrastructure/configuration-management/itil_runbooks/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - ITIL:

    - Runbooks: 

      - projects/itil/runbooks/index.md

      - GLPI:

        - Plugins:

          - projects/itil/runbooks/glpi/plugins/form_creator_new_form.md

- Operations: 

  - operations/index.md

- Contact Us: contact.md
